### ISSUE TITLE
Extend mwMimeType list for validation

### ISSUE THREAD

**Issue by ipandl** [mwaylabs/uikit#109]
You can see list with all possible types in here:
https://www.thoughtco.com/mime-types-by-content-type-3469108

**Comment by ipandl** [comment]
And there is minor bug with mw-file-upload directive and require attribute
![image](https://user-images.githubusercontent.com/13336471/28268581-1b18a95c-6aff-11e7-8c28-38423cc995a5.png)

**Comment by Zarlex** [comment]
Some browsers can not deal with the mimetypes or use a more generic one like `application/octet-stream`. It does not make sense to add all available mimetypes... Is there a certain mime that you need?
