### ISSUE TITLE
Enable resolve in modal windows

### ISSUE THREAD

**Issue by ipandl** [mwaylabs/uikit#11]
We need extended modal window with resolver, that means to have resolve method because now we are also using tables and filter inside of modal windows

**Comment by Zarlex** [comment]
I added the functionality that you can define resolve in the modal definition. The modal will be now displayed as soon as the template and the resolve things are resolved.
But thing is that as soon as you defined resolvers the user has to wait until they are resolved. We solved that issue for view changes by adding a `view-change-loading-spinner` that is displayed as long as the resolvers are resolved.
How should we handle this for modals?

**Comment by Zarlex** [comment]
@axelhodler maybe you have also an idea for that issue?
