### ISSUE TITLE
Filterable throws exception when search query param in url is unknown

### ISSUE THREAD

**Issue by yabdelmonem** [mwaylabs/uikit#137]
Exception message:
Filter named 'search' not found, did you add it to filterValues of the model?
  
Exception Stack trace:
{code}Error: Filter named 'search' not found, did you add it to filterValues of the model?
     at Filterable.<anonymous> <instance>/modules/039146fe.components.js:53:27448)
     at <instance>/portal/modules/039146fe.components.js:17:29864
     at Function.m.each.m.forEach <instance>/portal/modules/039146fe.components.js:17:30767)
     at Filterable.setFilters <instance>/portal/modules/039146fe.components.js:53:27182)
     at MwListCollection.<anonymous> <instance>/portal/modules/039146fe.components.js:48:15861)
     at processQueue <instance>/portal/modules/039146fe.components.js:11:14871)
     at <instance>/portal/modules/039146fe.components.js:11:15163
     at Scope.$eval <instance>/portal/modules/039146fe.components.js:11:27484)
     at Scope.$digest <instance>/portal/modules/039146fe.components.js:11:25127)
     at Scope.$apply <instance>/portal/modules/039146fe.components.js:11:27919){code}
  
User message:
No description was added by the user
  
  
  
Happened on page:
  <instance>/#/apps?qAttr=search&q=XYZ

**Comment by bugfrisch** [comment]
fix it
