### ISSUE TITLE
Blocker: v.1.19.0 doesn't hide the hidden columns

### ISSUE THREAD

**Issue by yabdelmonem** [mwaylabs/uikit#162]
Columns which are marked as hidden are no longer hidden by default.

**Comment by Zarlex** [comment]
What do you mean with marked as hidden? In case you mean that the attribute `hidden` is set it actually should work. 
There is a test case that is testing that case 
```js
it('is hidden when hidden attribute is set', function(){
      activeBreakPoint = 'md';
      this.setHeaderTemplate('<th mw-listable-header-bb hidden></th>');
      var isolatedScope = this.$headerEl.isolateScope();
      this.$timeout.flush();

      expect(isolatedScope.isVisible()).toBeFalsy();
    });
```
And i checked it in the sample portal where it is working

**Comment by yabdelmonem** [comment]
After retesting it looks like an issue which is caused by one of our runners, therefor i will close this ticket because the bug lies in the buildscripts on portal side or a maybe a caching problem in the runners.
