### ISSUE TITLE
MDM-14983, MDM-15472, MDM-15581: mwFileUpload crashes with $apply already in progress

### ISSUE THREAD

**Issue by yabdelmonem** [mwaylabs/uikit#206]
See:
- MDM-14983,
- MDM-15472,
- MDM-15581

We have the same issue when you upload an app/version

**Comment by bugfrisch** [comment]
very important, please fix asap

**Comment by bugfrisch** [comment]
alex?

**Comment by bugfrisch** [comment]
over 3 months for a fix and still open?
