### ISSUE TITLE
Remove trailing slash from requests

### ISSUE THREAD

**Issue by axelhodler** [mwaylabs/uikit#3]
e.g. when using

```javascript
this.setEndpoint('users/' + userId + '/preferences');
```

the uikit will prepend a slash `/` at the end such that the request goes to `[...]/preferences/` instead of `[...]/preferences`. This is unnecessary and leads to, should the user decide to do so, `/preferences/?someQueryParm=foo` which destroys the query parameter

**Comment by t-beckmann** [comment]
Why does it destroy the query parameter? Isn't the example just a valid URL?

**Comment by axelhodler** [comment]
> Isn't the example just a valid URL?

Good point, it is, and the query parameter works.

Still i would enjoy not having it added automatically since its confusing
