### ISSUE TITLE
Please add a method to the translation service so that it accepts dynamically loaded translations

### ISSUE THREAD

**Issue by mariusheil** [mwaylabs/uikit#31]
I have some translations that I need to dynamically load during runtime. I would like to pass these to the translation service. The easiest way for me would be to pass an object that includes multiple locales with translations at once, such as this:
`"translations":{
            "de_DE":{
              "myTitle":"Mein Titel"
            },
            "en_US":{
              "myTitle":"My Title"
            }
          }`
This method should extend the translations so that no duplicates exist when it is called multiple times during runtime.

**Comment by Zarlex** [comment]
> This method should extend the translations so that no duplicates exist when it is called multiple times during runtime.

What do you mean with that? Do you want to call the method several times with the same translation keys or with different ones? Do you want to replace existing translation or do you want to just add new ones?

**Comment by mariusheil** [comment]
When the method is called with some translations, it should use these. But it might happen that the method is called again with the same set of values because of a page reload, etc,...
It should simply overwrite the old values.
I think my explanation was a little weird.

**Comment by Zarlex** [comment]
I will extend the i18n service with the following methods that can be called during runtime:
```
...
extendForLocale: function(locale, translations){...},
extend: function(localesWithTranslations){... }
...
```
You can call those method everytime you want and it will extend the translation resources. Existing resources will be always overwritten. It will throw an error in case the local does not exist

```
i18n.extendForLocale('de_DE', {common: {helloWord: 'Hallo Welt'}});
i18n.extend({de_DE: {common: {helloWord: 'Hallo Welt'}}, en_US: {common: {helloWord: 'Hello World'}}};
```

Is that what you were thinking of?

**Comment by mariusheil** [comment]
yes, perfect :-)
