### ISSUE TITLE
css issues with shadows on modals

### ISSUE THREAD

**Issue by axelhodler** [mwaylabs/uikit#4]
![image](https://cloud.githubusercontent.com/assets/1504952/18439455/b8d2d43e-7905-11e6-94a2-aa8ae56c98e8.png)
- The footer throws a shadow over the background but the same shadow effect is missing on the body. You can see the shadow stops above the green line.
- The shadow inside of the modal between the footer and the body looks broken, the transition is not _fluid_

happens on newest chrome version and newest firefox

**Comment by Zarlex** [comment]
I don't get it. What do you mean with _over the background_ and _body_. The screenshot that you have attached looks ok
