### ISSUE TITLE
Precommit hook fail

### ISSUE THREAD

**Issue by ipandl** [mwaylabs/uikit#72]
We should have precommit hook in package.json inside project folder, not in uiKIT package.json. Can you remove precommit hook?

**Comment by Zarlex** [comment]
The git hooks in the uikit are needed for the uikit development to prevent that something broken is pushed by accident.
They will only take effect when you try to push something into the uikit repo. It should not affect the repo where you are using the uikit...
Check the hooks in your project `.git/hooks/{pre-commit, pre-push}` maybe there are some left overs from early days?
