### ISSUE TITLE
Add date range filter componet

### ISSUE THREAD

**Issue by ipandl** [mwaylabs/uikit#76]
Regarding customer requirement, it would be nice to have date range filter. 
Filter should have two date fields, from and to specific date. 
Please see attached images
![2017-04-22_1609](https://cloud.githubusercontent.com/assets/13336471/25305139/30b51736-2776-11e7-8f9f-d636d93b904c.png)
![untitled](https://cloud.githubusercontent.com/assets/13336471/25305138/30b3f4d2-2776-11e7-8e6c-9161cb8c15f8.png)

**Comment by Zarlex** [comment]
Fixed with https://github.com/mwaylabs/uikit/pull/77
mwUI.Relution got a new directive called `mw-sidebar-date-range-bb`
```html
 <div mw-sidebar-date-range-bb from-property="fromDate" to-property="toDate"></div>
```
You have to provide the translations for it because it is a relution directive
`common.fromDate` and `common.toDate`
