### ISSUE TITLE
mw-toggle has to be extended to support text as well

### ISSUE THREAD

**Issue by ipandl** [mwaylabs/uikit#83]
![image](https://cloud.githubusercontent.com/assets/13336471/25956903/4f7912ac-366d-11e7-8ad9-d59f290468a9.png)

**Comment by Zarlex** [comment]
It doesn't look pleasing when you put a long text into a toggle. Actually the toggle should not have any text (probably also no icon) at all. Fixed it for the public filter bar by adjusting the label and using a checkbox: https://github.com/mwaylabs/uikit/pull/97
