### ISSUE TITLE
Extend collection with possibility to save sortOrder

### ISSUE THREAD

**Issue by ipandl** [mwaylabs/uikit#84]
It would be great if user could save the last selected sort option for his collection. Now we are using predefined sortOrder option from collection to initialy sort our list.

How to test:
1. User navigate to page where we are using some list
2. He is changing his sort option by clicking on another column header
3. He goes to other page
4. He returns to previous page and he can see again predefined sorting option

**Comment by stefanjauker** [comment]
+1
I have a some of customer with this feature request.

**Comment by Zarlex** [comment]
I will have look at it
