### ISSUE TITLE
mwCheckboxGroup should also work with Backbone Relution.EnumCollection 

### ISSUE THREAD

**Issue by drisoftie** [mwaylabs/uikit#90]
The directive mwCheckboxGroup checks hardcoded for the idAttribute of the provided model inside the mwCollection. This causes issues with Backbone EnumCollections that don't have the idAttribute value anymore. A possible solution would be to give options to set a mapping property that determines what needs to be checked.

**Comment by drisoftie** [comment]
see https://github.com/mwaylabs/uikit/pull/91 for a suggestion

**Comment by Zarlex** [comment]
mwModel should have always a modelId
